### PR TITLE
chore: OP-546 uplift repo to add linting and husky

### PR DESCRIPTION
**Pull request by iaindurham**
- fix linting errors

### Issue Link:

OP-546

### What does it do?

Up lift the repo to use our internal code style enforced with eslint rule and husky

---

#### Notes to reviewers

1. There is quite a few variable renaming but there is no changes to functionality
2. The tests are still in Mocha, this is intentional as the repo needs to be uplifted before we can convert the tests (which will be done in a different ticket)
2. It would be easiest to review if this was reviewed by ignoring whitespace in the code as a lot of the changes are changing from spaces to tabs.

### CODE REVIEW

**Review by edmundcong — APPROVED** [review]
Ignored whitespace changes. Everything LGTM 👍

**Review by mingli-trend — APPROVED** [review]
I admire your work of 400 commits for OP-546... 

Still not sure why we have different indent style and size for different file types.

**Comment by sam-doomguy** [comment]
@iaindurham I recommend not converting tests on this repo as we want to stop using it and replace it with AWS SDK v3: https://www.npmjs.com/package/@aws-sdk/client-dynamodb

**Review by sam-doomguy — APPROVED** [review]

**Comment by iaindurham** [comment]
@mingli-trend 
> I admire your work of 400 commits...

It has been a labour of love ❤️ 

> Still not sure why we have different indent style and size for different file types.

Are you referring to the different indentation in the [editorconfig](https://github.com/cloudconformity/dynamodb-driver/pull/6/files#diff-0947e2727d6bad8cd0ac4122f5314bb5b04e337393075bc4b5ef143b17fcbd5b) file?

Not sure about the `package.json` but `*.yml` files need to use spaces and indentions need to be 2.

**Comment by iaindurham** [comment]
@sam-doomguy thanks for the heads up that is really cool, look forward to seeing the Epic to introduce this to the code base 😄 

I think that I will convert them anyway as there isn't many tests, I really want to remove it from everywhere and no idea how long it will take until we actually move to SDK v3 🙂

**Comment by sam-doomguy** [comment]
@iaindurham Roger that. That’s your call. Just wanted you to know the direction.

**Pull request merged**
